### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Nightsquid7** [Nightsquid7/AniMusic2#1]
User should be able to view anime songs organized by anime
User should be able to search Anime by name
User should be able to filter songs within an anime by ending/opening
Anime Should be sorted by opening number
User should be able to sign in with Spotify or Apple Music
User should be able to play songs from the app 
User should be able to add songs to their music library
User should be able to add playlists to their music library
Playlists should be able to be filtered by opening or ending
User should be able to bookmark/save music within the app?

User should be able to view basic song data:
- Song name
- Artist
- Song type - opening, ending, special?
- Episodes
- Opening number
- Movie/Ova?

Views
Login screen -> 
	Anime List -> 
		Song Cell View (track image thumbnail, opening/ending, number, song name) -> 
			SongView (track image, song name, artist, opening/ending, number, play controls)
	Settings View ->

**Comment by ahctang** [comment]
Hmm i think we should start with the crawler to harvest the anime info. Maybe we can start by doing like last season.
